# Generated by Django 5.1.5 on 2025-01-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_ideastar_idea_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtool',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='devtool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일지'),
        ),
        migrations.AlterField(
            model_name='devtool',
            name='kind',
            field=models.CharField(max_length=100, verbose_name='개발 툴 종류'),
        ),
        migrations.AlterField(
            model_name='devtool',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일지'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(upload_to='ideas/', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(default=0, verbose_name='관심도'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
    ]
