# Generated by Django 5.1.4 on 2025-01-09 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='개봉년도')),
                ('director', models.CharField(max_length=100, verbose_name='감독')),
                ('actors', models.CharField(max_length=200, verbose_name='주연')),
                ('genre', models.CharField(choices=[('Action', '액션'), ('Comedy', '코미디'), ('Drama', '드라마'), ('SF', 'SF'), ('Horror', '호러'), ('Romance', '로맨스')], max_length=20, verbose_name='장르')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('running_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='러닝타임(분)')),
                ('review_text', models.TextField(verbose_name='리뷰')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
